/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appjoyeriayuler.moduloCliente;

import appjoyeriayuler.securityModule.usuario.ControlSesionUsuario;
import appjoyeriayuler.securityModule.usuario.FormMenuPrincipal;
import appjoyeriayuler.shared.MensajeSistema;

import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class FormRegistrarCliente extends javax.swing.JFrame {

    controlRegistrarCliente controlador = new controlRegistrarCliente();
    /**
     * Creates new form FormRegistrarCliente
     */
    public FormRegistrarCliente() {
        initComponents();        
        setResizable(false);
        setLocationRelativeTo(null);
        desactivarCampos();
    }
    
    // Método para desactivar los campos
    public void desactivarCampos(){
        txtCliente.setEnabled(false);
        txtRUC.setEnabled(false);
        txtTelefono.setEnabled(false);
        btnRegistrarCliente.setEnabled(false);
    }
    
    public void desactivarCamposSinCliente(){
        txtRUC.setEnabled(false);
        txtTelefono.setEnabled(false);
        btnRegistrarCliente.setEnabled(false);
    }

    // Método para habilitar los campos cuando el DNI es válido
    public void habilitarCampos() {
        txtRUC.setEnabled(true);
        txtTelefono.setEnabled(true);
        btnRegistrarCliente.setEnabled(true);
    }

    private boolean validarClienteCompleto(String nombre) {
    if (!controlador.esNombreClienteValido(nombre)) {
        return false;
    }

    if (!controlador.esNombreMinimo(nombre)) {
        return false;
    }

    if (!controlador.contieneSoloLetras(nombre)) {
        return false;
    }

    if (!controlador.esNombreMaximo(nombre)) {
        return false;
    }

    return true;
}
    
    // Método para validar el DNI
    private boolean validarDNICompleto(String dni) {
    if (!controlador.esDniValido(dni)) {
        return false;
    }
    if (!controlador.esNumerico(dni)) {
        return false;
    }

    if (!controlador.esLongitudValida(dni)) {
        return false;
    }

    if (controlador.dniExiste(dni)) {
        return false;
    }

    return true;
}

// Método para validar el nombre del cliente
    private boolean validarRUCCompleto(String ruc) {
    if (controlador.esRucVacio(ruc)) {
        return true; // RUC vacío es válido (lo puedes almacenar como null o 0)
    }

    if (!controlador.esRucNumerico(ruc)) {
        return false;
    }

    if (!controlador.esRucLongitudValida(ruc)) {
        return false;
    }

    if (controlador.rucExiste(ruc)) {
        return false;
    }

    return true;
}

    private boolean validarTelefonoCompleto(String telefono) {
    if (controlador.esTelefonoVacio(telefono)) {
        return true;
    }

    if (!controlador.esTelefonoNumerico(telefono)) {
        return false;
    }

    if (!controlador.esTelefonoLongitudValida(telefono)) {
        return false;
    }

    if (controlador.telefonoExiste(telefono)) {
        return false;
    }

    return true;
}

    private void limpiarCampos() {
    txtDNI.setText("");
    txtCliente.setText("");
    txtRUC.setText("");
    txtTelefono.setText("");
}


    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));

        txtDNI.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI.setForeground(new java.awt.Color(0, 0, 0));
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
        });

        txtCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });

        txtRUC.setBackground(new java.awt.Color(255, 255, 255));
        txtRUC.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Registro de clientes");

        btnRegistrarCliente.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(51, 153, 255));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnMenu.setText("Volver a menú principal");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("RUC:");

        jLabel5.setText("Telefono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnMenu)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
         String dni = txtDNI.getText().trim();

    if (!controlador.esDniValido(dni)) {
        desactivarCampos();  // Campo vacío → desactiva todo
    }
    // No habilites nada aún, esperas al Enter
    }//GEN-LAST:event_txtDNIKeyReleased

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        String dni = txtDNI.getText().trim();

    if (!validarDNICompleto(dni)) {
        desactivarCampos();
        return;
    }

    txtCliente.setEnabled(true);
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        String nombre = txtCliente.getText().trim();

    if (!controlador.esNombreClienteValido(nombre)) {
        desactivarCamposSinCliente();
    }
    // No actives nada aquí, esperas al Enter (igual que con DNI)
    }//GEN-LAST:event_txtClienteKeyReleased

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        String nombre = txtCliente.getText().trim();

    if (!validarClienteCompleto(nombre)) {
        desactivarCamposSinCliente();
        return;
    }

    habilitarCampos();
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
       // Obtener RUC
        String ruc = txtRUC.getText().trim();
        if (!validarRUCCompleto(ruc)) return;

        // Obtener Teléfono
        String telefono = txtTelefono.getText().trim();
        if (!validarTelefonoCompleto(telefono)) return;

        // Obtener DNI y Cliente
        String dni = txtDNI.getText().trim();
        String cliente = txtCliente.getText().trim();

        // Registrar cliente usando el controlador
        if (controlador.registrarCliente(dni, cliente, ruc, telefono)) {
            limpiarCampos();
            desactivarCampos();
            txtDNI.requestFocus(); // Volver a enfocar para registrar otro cliente
        }    
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // Obtener privilegios desde la sesión actual
    /*
    List<String> privilegios = ControlSesionUsuario.getPrivilegios();

    // Cerrar el formulario actual
    this.dispose();

    // Abrir el menú principal con privilegios
    new FormMenuPrincipal(privilegios).setVisible(true);*/
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
